# Generated by Django 4.2.30 on 2026-05-24 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('classroom', models.CharField(choices=[('Bumblebees', 'Bumblebees 🐝'), ('Butterflies', 'Butterflies 🦋'), ('Ladybugs', 'Ladybugs 🐞')], default='Bumblebees', max_length=20)),
                ('avatar_emoji', models.CharField(choices=[('🦁', 'Lion 🦁'), ('🐯', 'Tiger 🐯'), ('🐘', 'Elephant 🐘'), ('🐼', 'Panda 🐼'), ('🦊', 'Fox 🦊'), ('🐨', 'Koala 🐨'), ('🦖', 'Dino 🦖'), ('🦄', 'Unicorn 🦄'), ('🐰', 'Bunny 🐰'), ('🐸', 'Frog 🐸'), ('🦉', 'Owl 🦉'), ('🐝', 'Bee 🐝'), ('🦋', 'Butterfly 🦋'), ('🐳', 'Whale 🐳'), ('🦀', 'Crab 🦀')], default='🦁', max_length=5)),
                ('avatar_color', models.CharField(choices=[('#FFADAD', 'Pastel Red'), ('#FFD6A5', 'Pastel Orange'), ('#FDFFB6', 'Pastel Yellow'), ('#CAFFBF', 'Pastel Green'), ('#9BF6FF', 'Pastel Cyan'), ('#A0C4FF', 'Pastel Blue'), ('#BDB2FF', 'Pastel Purple'), ('#FFC6FF', 'Pastel Pink')], default='#A0C4FF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present ☀️'), ('absent', 'Absent 🌙'), ('late', 'Late ⏰')], default='present', max_length=10)),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy 😊'), ('excited', 'Excited 🤩'), ('sleepy', 'Sleepy 🥱'), ('silly', 'Silly 🤪'), ('sad', 'Sad 😢')], max_length=10, null=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.CharField(default='child', max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
