# Generated by Django 4.2.30 on 2026-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Avatar Colors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvatarEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avatar Emoji',
                'verbose_name_plural': 'Avatar Emojis',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Classroom Options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_period',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (5 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 11:59 PM)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_emoji',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(max_length=50),
        ),
    ]
