# Generated by Django 4.2.30 on 2026-05-24 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_avatarcolor_avataremoji_classroomoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pin_code',
            field=models.CharField(default='1234', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN code must be exactly 4 digits.')]),
        ),
    ]
