# Generated by Django 4.2.30 on 2026-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_assignmentgroup_supportengineer_supportticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportengineer',
            name='group',
        ),
        migrations.AddField(
            model_name='supportengineer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='engineers', to='attendance.assignmentgroup'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
