# Generated by Django 4.2.30 on 2026-06-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0006_remove_supportengineer_group_supportengineer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportengineer',
            name='password',
            field=models.CharField(default='engineer123', max_length=128),
        ),
        migrations.CreateModel(
            name='TeacherSupportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_raise_tickets', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
